// Generates the package's embedded static assets as ES modules under
// generated/:
//
//   generated/shader-sources.js — every GLSL file under shaders/**,
//     keyed by its shaders/-relative path.  shader-loader.js resolves
//     #include directives against this map at runtime, so the published
//     package needs no server to host the shader tree.
//
//   generated/world-data.js — worlds/manifest.json plus every world
//     JSON it lists.  worlds.js installs them synchronously.
//
// Run by `npm run build` (scripts/build.mjs) before esbuild; generated/
// is gitignored — the .glsl/.vert/.frag and .json files stay the
// editable sources of truth.

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outDir = path.join(pkgDir, 'generated')
mkdirSync(outDir, { recursive: true })

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const p = path.join(dir, name)
    return statSync(p).isDirectory() ? walk(p) : [p]
  })

// Shaders → { 'main/main.vert': '…', … }
const shadersDir = path.join(pkgDir, 'shaders')
const shaderEntries = walk(shadersDir)
  .sort()
  .map((file) => {
    const rel = path.relative(shadersDir, file).split(path.sep).join('/')
    return `  ${JSON.stringify(rel)}: ${JSON.stringify(readFileSync(file, 'utf8'))},`
  })
writeFileSync(
  path.join(outDir, 'shader-sources.js'),
  `// Generated by scripts/gen-assets.mjs — do not edit.  Sources of truth\n` +
    `// are the GLSL files under shaders/**.\n` +
    `export const SHADER_SOURCES = {\n${shaderEntries.join('\n')}\n}\n`,
)

// Worlds → manifest + { key: worldJson }
const worldsDir = path.join(pkgDir, 'worlds')
const manifest = JSON.parse(readFileSync(path.join(worldsDir, 'manifest.json'), 'utf8'))
const worlds = {}
for (const m of manifest.worlds) {
  worlds[m.key] = JSON.parse(readFileSync(path.join(worldsDir, `${m.key}.json`), 'utf8'))
}
writeFileSync(
  path.join(outDir, 'world-data.js'),
  `// Generated by scripts/gen-assets.mjs — do not edit.  Sources of truth\n` +
    `// are worlds/manifest.json and the worlds/*.json it lists.\n` +
    `export const WORLDS_MANIFEST = ${JSON.stringify(manifest, null, 2)}\n\n` +
    `export const WORLD_DATA = ${JSON.stringify(worlds, null, 2)}\n`,
)

console.log(`generated shader-sources.js (${shaderEntries.length} files) + world-data.js (${manifest.worlds.length} worlds)`)
